### ISSUE TITLE
error with database_downloader.sh

### ISSUE THREAD

**Issue by Wanli-HE** [leaemiliepradier/PlasForest#1]
hi !

when i  "bash database_downloader.sh "

"All sequences were downloaded correctly. Good!
Program finished without error."

but also a line:
"database_downloader.sh: line 41: 24585 Segmentation fault      makeblastdb -in plasmid_refseq.fasta -dbtype nucl -parse_seqids"

is that a error?

**Comment by Wanli-HE** [comment]
> hi !
> 
> when i "bash database_downloader.sh "
> 
> "All sequences were downloaded correctly. Good!
> Program finished without error."
> 
> but also a line:
> "database_downloader.sh: line 41: 24585 Segmentation fault makeblastdb -in plasmid_refseq.fasta -dbtype nucl -parse_seqids"
> 
> is that a error?

(plasforest) PlasForest$ ncbi-blast+/ncbi-blast-2.10.1+/bin/makeblastdb -in plasmid_refseq.fasta -dbtype nucl -parse_seqids


Building a new DB, current time: 10/17/2020 11:43:22
New DB name:   /mibi/users/Wanli/PlasForest/plasmid_refseq.fasta
New DB title:  plasmid_refseq.fasta
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B

No volumes were created.

Error: mdb_env_open: Cannot allocate memory

**Comment by leaemiliepradier** [comment]
The file plasmid_refseq.fasta is quite large (~2.3GB). How much RAM memory does your computer have?
If memory is insufficient on your computer, you might want to launch `makeblastdb` from another computer with more RAM. Then, just copy the output files to your PlasForest-master folder, and it should work just fine. `makeblastdb` should output the following files:
- plasmid_refseq.fasta.mfc
- plasmid_refseq.fasta.nhr
- plasmid_refseq.fasta.nin
- plasmid_refseq.fasta.nog
- plasmid_refseq.fasta.nsd
- plasmid_refseq.fasta.nsi
- plasmid_refseq.fasta.nsq

Please let me know if the issue persists.

Best,
Léa

**Comment by Wanli-HE** [comment]
thanks for your answer. i had solved, because the memory is not enough
