### ISSUE TITLE
hi， it seems like you updat something, another error  like below

### ISSUE THREAD

**Issue by Wanli-HE** [leaemiliepradier/PlasForest#14]
PlasForest: a homology-based random forest classifier for plasmid identification.
(C) Lea Pradier, Tazzio Tissot, Anna-Sophie Fiston-Lavier, Stephanie Bedhomme. 2020.
Traceback (most recent call last):
  File "PlasForest.py", line 311, in <module>
    main(sys.argv[1:])
  File "PlasForest.py", line 147, in main
    finalfile = plasforest_predict(features, showFeatures, besthits, verbose, attributed_IDs, attributed_identities, nthreads)
  File "PlasForest.py", line 289, in plasforest_predict
    plasforest.n_jobs = int(nthreads)
NameError: name 'plasforest' is not defined

**Comment by tazziotissot** [comment]
Yes, we tried to implement a request without testing it, but it messed up with the globals.
We have partially reverted to the previous version. Let me know if it's not working.

**Comment by Wanli-HE** [comment]
> Yes, we tried to implement a request without testing it, but it messed up with the globals. We have partially reverted to the previous version. Let me know if it's not working.

ok, are you trying to fixing the problem that when running plasforest must be in the plasforest fold? i guess  because the globals thing that causes every time when you are running it, you  must in the fold with ”plasforest.py“ script

**Comment by Wanli-HE** [comment]
> > Yes, we tried to implement a request without testing it, but it messed up with the globals. We have partially reverted to the previous version. Let me know if it's not working.
> 
> ok, are you trying to fixing the problem that when running plasforest must be in the plasforest fold? i guess because the globals thing that causes every time when you are running it, you must in the fold with ”plasforest.py“ script. 

and honestly, it is really unconvenient.

**Comment by tazziotissot** [comment]
Yes, I agree that it could be inconvenient for most users.
Finally, we implemented this feature. You can download the latest version, it was tested and works from any directory as long as you precise the paths for the .sav file and the plasmid database.

**Comment by Wanli-HE** [comment]
> Yes, I agree that it could be inconvenient for most users. Finally, we implemented this feature. You can download the latest version, it was tested and works from any directory as long as you precise the paths for the .sav file and the plasmid database.

cool， it works， it had tested it
