### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'plasforest.sav'

### ISSUE THREAD

**Issue by Leytoncito** [leaemiliepradier/PlasForest#4]
Hello!
When I try this :
`for file in *.fna; do python ../../../softwares/PlasForest/PlasForest.py -b -i $file -o ${file%%.fna}.csv --threads 8; done`
 I get this for each fasta file:

Traceback (most recent call last):
  File "../../../softwares/PlasForest/PlasForest.py", line 45, in <module>
    plasforest = pickle.load(open("plasforest.sav","rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'plasforest.sav'

**the test turned out well.

Help me please.
thanks in advance
Benjamin Leyton

**Comment by Leytoncito** [comment]
I may have to put the ".sav" file in the working directory

**Comment by leaemiliepradier** [comment]
Hi,

Indeed, PlasForest.py looks for the SAV file (which contains the binaries for the random forest classifier) in the current working directory.
Here you have two solutions:
- either you call PlasForest from its directory
- or you modify PlasForest.py to write the absolute path of the SAV file: ```pickle.load(open("path/to/PlasForest/plasforest.sav","rb"))```
Else, you might also want to try adding the PlasForest directory to your path: ```export PATH=$PATH:path/to/PlasForest```. Though, I'm not sure this solution may work.

Let me know if any of these solutions has been helpful.
Léa

**Comment by Leytoncito** [comment]
Hello.

this is what i did:
 
`for file in /ruta/de/entrada/fna/*.fna; do python PlasForest.py -b -i $file -o /ruta/de/salida/${file%%.fna}.csv --threads 8; done`

It worked.

I hope it helps you
